version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: websocket_server
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - ./server:/app