version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-server
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - ./server:/app
  db:
    image: mysql:8.0
    container_name: go-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
